### ISSUE TITLE
iOS 10 不能使用吗？

### ISSUE THREAD

**Issue by chnt7305** [bumaociyuan/ios-ipa-server#12]
我在 VPS上搭建了　但是点击下载没有反应　未越狱的情况下不能使用吗？

**Comment by bumaociyuan** [comment]
亲测可用

**Comment by chnt7305** [comment]
这个对 ipa 文件有要求吗？方便给我一个测试链接吗？

**Comment by bumaociyuan** [comment]
没有要求，你本机可以用吗？
VPS是什么版本的
我只在Ubuntu14.04上测试过

**Comment by chnt7305** [comment]
VPS Debian 7 x86
本机可以用是什么意思？

**Comment by bumaociyuan** [comment]
Mac 也可以使用

**Comment by chnt7305** [comment]
我只有一个 iPad mini 2
没有其他 iOS 设备了

**Comment by bumaociyuan** [comment]
没有公网服务器，局域网测试了，iOS10可以用
ipa文件名不要用中文和空格

**Comment by bumaociyuan** [comment]
@chnt7305 可以用了吗？

**Comment by chnt7305** [comment]
@bumaociyuan 还没试，我会反馈结果的。
