### ISSUE TITLE
not an -iphone crushed PNG file

### ISSUE THREAD

**Issue by mzying2013** [bumaociyuan/ios-ipa-server#19]
.//icon.png : not an -iphone crushed PNG file
pngdefry : seen 1 file(s), wrote 0 file(s)

上面的警告是什么意思，我在目录下已经放了一张icon.png图片，但是网页刷新后，图片消失了。

**Comment by bumaociyuan** [comment]
@mzying2013 什么系统

**Comment by mzying2013** [comment]
Mac OS  10.12.2
