### ISSUE TITLE
阿里云服务器使用，可以正常访问，  安装证书时出现网址绑定错误

### ISSUE THREAD

**Issue by miss61008596** [bumaociyuan/ios-ipa-server#20]
![image](https://cloud.githubusercontent.com/assets/6361237/23601954/12ab56cc-0289-11e7-8826-2b0ec3efc6b9.png)
公网地址是120.27.124.108，内网地址10.174.244.202，证书绑定到了内网地址，访问需要用公网地址

**Comment by bumaociyuan** [comment]
@miss61008596 你可以手动生成公网证书

**Comment by miss61008596** [comment]
用openssl 生成证书么？ios-ipa-server这边需不需要配置啥

**Comment by bumaociyuan** [comment]
@miss61008596 要解决你这个问题，我给你加一个手动设置ip的参数吧

**Comment by miss61008596** [comment]
@跪谢老大 ，666666

**Comment by miss61008596** [comment]
@bumaociyuan   
![image](https://cloud.githubusercontent.com/assets/6361237/23602953/e11f5928-028d-11e7-9ff7-a552d5cc6be9.png)
是改这个参数对么？@_@

**Comment by bumaociyuan** [comment]
@miss61008596 你不用改代码，`npm install -g ios-ipa-server`

**Comment by miss61008596** [comment]
@bumaociyuan  真是炫酷的体验，棒极了
