### ISSUE TITLE
10.3上已经安装了证书 还是提示无法连接，10.3以下固件是正常的

### ISSUE THREAD

**Issue by lylh** [bumaociyuan/ios-ipa-server#23]
10.3上已经安装了证书 还是提示无法连接，10.3以下固件是正常的

**Comment by bumaociyuan** [comment]
@lylh 10.3 确实有问题，我还没有升级手机，过几天再看

**Comment by lylh** [comment]
@bumaociyuan 已经找到解决的方法了
On iOS 10.3:
Settings > General > About (logically...) > Certificate Trust Settings > Enable Full Trust for Root Certificates
参考：
https://forums.developer.apple.com/message/212408#212408

https://forums.developer.apple.com/thread/71789

**Comment by bumaociyuan** [comment]
@lylh 果然可以，谢谢
