### ISSUE TITLE
是否支持多级目录？

### ISSUE THREAD

**Issue by mrdaios** [bumaociyuan/ios-ipa-server#24]
@bumaociyuan 🙏首先非常感谢。

我们多个app放在多个目录并且有多个版本。
x1APP
--10.10.1
--10.10.2
--10.10.3
x2APP
--11.10.1
--11.10.2
--11.10.3

**Comment by bumaociyuan** [comment]
@mrdaios 不好意思暂不支持
你可以自己写个页面，加两个link链接到两个`ios-ipa-server`上

**Comment by mrdaios** [comment]
好的，谢谢
