### ISSUE TITLE
ipa安装慢

### ISSUE THREAD

**Issue by ramy612** [bumaociyuan/ios-ipa-server#28]
20多M的安装包开始安装之后长时间停留在“等待中...”的状态，这跟fs-extra组件读取文件的速度比较慢有关系么？等待时间太长了，请问这可能是什么问题导致的呢？

**Comment by bumaociyuan** [comment]
@ramy612 我经常安装超过80M的ipa，并没觉得特别慢

**Comment by ramy612** [comment]
我这50M的一个ipa安装了7分钟，前6分多种一直是等待中的状态

**Comment by bumaociyuan** [comment]
@ramy612 前面比较长时间的“等待中...” 是系统正在下载ipa

我实测一下 
5:23开始安装

**Comment by ramy612** [comment]
@bumaociyuan 嗯，所以这个是下载慢喽？ipa我放在阿里云上了，公司的wifi百兆网络，这下载不至于如此慢吧……

**Comment by bumaociyuan** [comment]
@ramy612 我把ipa放到局域网的linux服务器上可能速度比较块

**Comment by ramy612** [comment]
@bumaociyuan thx，给力，求加个微信好友sunshine_panda
