### ISSUE TITLE
Ubuntu 12.04.5 LTS \n \l 安装时提示一下错误

### ISSUE THREAD

**Issue by lyt3251** [bumaociyuan/ios-ipa-server#29]
能提供一下错误的解决办法吗？谢谢！
npm install -g ios-ipa-server 错误提示和下面一样
[
<img width="787" alt="2017-08-24 5 33 48" src="https://user-images.githubusercontent.com/10862334/29660040-bec7183e-88f2-11e7-8994-7abcde6a9c94.png">
](url)

**Comment by bumaociyuan** [comment]
express 都安装失败了，应该是你网络的问题 @lyt3251
