### ISSUE TITLE
无法连接到，我电脑的ip

### ISSUE THREAD

**Issue by songxing10000** [bumaociyuan/ios-ipa-server#30]
![image](https://user-images.githubusercontent.com/10040131/30255709-3d139cec-96d8-11e7-900d-bd55899067e4.png)

![image](https://user-images.githubusercontent.com/10040131/30255646-d2f19a76-96d7-11e7-91bc-118ca86844ed.png)

![image](https://user-images.githubusercontent.com/10040131/30255671-f25750e0-96d7-11e7-9e68-d04803ef04ed.png)

**Comment by bumaociyuan** [comment]
@songxing10000 https://github.com/bumaociyuan/ios-ipa-server/issues/23

**Comment by songxing10000** [comment]
回复真快

**Comment by bumaociyuan** [comment]
邮件提醒

**Comment by songxing10000** [comment]
已解决，把这个开关，打开
![image](https://user-images.githubusercontent.com/10040131/30255760-7b51c272-96d8-11e7-977c-a010c3d47a75.png)

**Comment by songxing10000** [comment]
如果手机设置了代码，也会提示，没法连接ip

**Comment by songxing10000** [comment]
如果Windows上能用你这个吗

**Comment by bumaociyuan** [comment]
可以
