### ISSUE TITLE
提示无法连接到“192.168.0.101”

### ISSUE THREAD

**Issue by xhanglizhu** [bumaociyuan/ios-ipa-server#37]
在手机Safari中打开 download页面，点击下载，提示点击安装后会自动下载app，请返回桌面查看，点击“好”之后，提示无法连接到“192.168.0.101”
iOS 11.2.1
描述文件中有ios-ipa-server 192.168.0.101 Custom CA

**Comment by bumaociyuan** [comment]
@xhanglizhu 签名问题

**Comment by xhanglizhu** [comment]
@bumaociyuan  感谢。已经解决了，需要设置信任。Settings > General > About (logically...) > Certificate Trust Settings > Enable Full Trust for Root Certificates

**Comment by xhanglizhu** [comment]
@bumaociyuan  download的页面没有显示版本号和更新日期，怎么解决？

**Comment by bumaociyuan** [comment]
1.2.2 已修复
