### ISSUE TITLE
抛出错误

### ISSUE THREAD

**Issue by Z-fly** [bumaociyuan/ios-ipa-server#43]
![](https://camo.githubusercontent.com/de06ed84bc410a2b900e8e3e9012a7a6a36f30c8/68747470733a2f2f73312e617831782e636f6d2f323031382f31302f30312f6931323270462e6a7067)

**Comment by bumaociyuan** [comment]
OS X
Ubuntu
CentOS
其他平台未测试

@Z-fly windows 问题多，建议找个linux
