### ISSUE TITLE
安装之后打不开

### ISSUE THREAD

**Issue by xmw1992** [bumaociyuan/ios-ipa-server#44]
我的ipa可以下载，但是老是打不开，就是一个灰色的图标，是否是我打包的问题呢，我是用xcode直接打包的，然后用签名工具重新签名，请问问题出在哪里，是否是签名选择的证书有问题啊

**Comment by bumaociyuan** [comment]
应是签名证书的问题

**Comment by xmw1992** [comment]
我是使用了您项目中的.iosxxx下面生成的证书其中的一个.req证书去苹果开发者后台进行生成.cer和描述文件的，然后对我的ipa进行重签名，之后就是可以安装，但是打不开，您可以指导一下我这个过程哪里有错误么，十分感谢🙏
