### ISSUE TITLE
IOS 14.5提示无法安装

### ISSUE THREAD

**Issue by Colocasia** [bumaociyuan/ios-ipa-server#49]
RT

**Comment by bumaociyuan** [comment]
https://github.com/bumaociyuan/ios-ipa-server/issues/23 试试

**Comment by Colocasia** [comment]
14.4是正常的，证书信任那里没有问题呢

**Comment by Colocasia** [comment]
补充一下，手动安装也是成功的，网页上安装不了，提示无法安装

**Comment by Colocasia** [comment]
@bumaociyuan

**Comment by Colocasia** [comment]
> #23 试试

这个好像不是这个问题

**Comment by Colocasia** [comment]
@bumaociyuan 这个问题并不是 #23 这个问题  IOS14.5依然提示无法安装 但是IOS14.4是正常的

**Comment by provswin** [comment]
@Colocasia 解决了么，我也遇到了这个问题
