### ISSUE TITLE
where the plist and ipa should be placed?

### ISSUE THREAD

**Issue by huanhuang** [bumaociyuan/ios-ipa-server#7]
what mean /path/of/ipa? where the plist and ipa should be placed?

**Comment by bumaociyuan** [comment]
@huanhuang ipa 可以放在任何位置，plist是自动生成的

**Comment by huanhuang** [comment]
谢啦！重新下载安装可以了。
这个只能在局域网访问是不？

**Comment by bumaociyuan** [comment]
@huanhuang 可以部署在服务器上，支持linux
